#!/bin/bash

# Define the device and mount point
DEVICE="/dev/sdb"
MOUNT_POINT="/home/vicuser/data-disk"

# Check if script is run as root
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root!" >&2
  exit 1
fi

# Check if /dev/sdb exists
if ! lsblk | grep -q "sdb"; then
  echo "Partition $DEVICE not found. Exiting..." >&2
  exit 1
fi

echo "Creating xfs filesystem on virtual hard drive..."
mkfs.xfs $DEVICE

echo "Creating data-disk directory..."
mkdir $MOUNT_POINT

echo "Mounting hard drive on /home/vicuser/data-disk ..."
mount $DEVICE $MOUNT_POINT

echo "Setting permissions..."
chown vicuser $MOUNT_POINT
chgrp vicuser $MOUNT_POINT

# Check if the device is mounted on the mount point
if findmnt -rn -S "$DEVICE" -T "$MOUNT_POINT" > /dev/null; then
    echo "Hard drive successfully mounted $DEVICE on $MOUNT_POINT"
else
    echo "Failed to mount $DEVICE on $MOUNT_POINT"
fi
